steps:
  docker:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      pull_image: true
      registry: git.bluemedia.dev
      repo: git.bluemedia.dev/bluemedia/nginx-live
      platforms: linux/amd64,linux/arm/v6,linux/arm64/v8
      tag: latest

  notify:
    image: git.bluemedia.dev/bluemedia/woodpecker-email
    settings:
      from:
        from_secret: smtp_notify_email
      host:
        from_secret: smtp_notify_host
      username:
        from_secret: smtp_notify_username
      password:
        from_secret: smtp_notify_password
      recipients_only: true
      recipients:
        from_secret: smtp_notify_recipients
    when:
      - status: [ failure ]
